### PR TITLE
converted repo into proper package (name: tad; installable via setup.py)

### PR DESCRIPTION
**Pull request by arne-cl**
Dear David,

I added some boilerplate to your code, which would make it installable
via `python setup.py install` (under the assumption that `setuptools`
is already installed on the system).

The code is then importable via `from tad import TADClassifier` and the demo
can be launched from the command line with `tad_demo`.

Cheers,
Arne

### CODE REVIEW

**Comment by dmarx** [comment]
Hey Arne,

I'm not accustomed to setting up my projects for distribution as packages. Some questions:
1. What is the purpose of the "build" and "src" folders? They seem redundant, and I noticed that setup.py only points to the "src" folder you created. I'm guessing these folders are an artifact of your development environment (eclipse?)
2. Is there any particular reason you organized the folder structure the way you did? I originally organized the package so the main function was in `TADClassifier.tad_classify`, but now it's in `tad.TADClassifier.tad_classify`. Is there any particular reason you nested the module under the additional "tad" folder? I'm inclined to move everything up a level and eliminate the "tad" folder, but I'm open to hear your reasoning before doing so.

Thanks for submitting the pull request!

**Comment by arne-cl** [comment]
Hi David,

I'm not not an expert regarding `setup.py` configuration either. The `build` folder is generated when you run your `setup.py`. It is redudant in the sense that you should exclude it from your repo. (I think it is used to build the necessary files for distributing your package via PyPI. It has nothing to do with your IDE -- I'm not even using one.)

Of course you can move everything up one level. I just chose `tad` because it is a very short name that is still available on PyPI;) If it's just about the length of the "qualified" function name `tad.TADClassifier.tad_classify`, you could also add `from TADClassifier import tad_classify` to the `__init__.py` file in the `tad` directory, which would make the function available under the path `tad.tad_classify`.

Best,
Arne

**Comment by dmarx** [comment]
You're totally right about `build`, my bad.
RE:tad, that was sort of my thinking as well, except in the other direction: "tad" seems like such a great name for a package, I sort of feel bad wasting it on this tool! In any event, thanks for contributing. I'll probably be pushing this on to PyPi in the near future, and I may take your advice and just use "tad" for the package name.

**Comment by arne-cl** [comment]
> RE:tad, that was sort of my thinking as well, except in the other
> direction: "tad" seems like such a great name for a package, I sort of
> feel bad wasting it on this tool! In any event, thanks for contributing.

That seems like a very good reason to stick to `TADClassifier`.

**Pull request merged**
